### ISSUE TITLE
Demo fails in latest Chrome?

### ISSUE THREAD

**Issue by canadaduane** [garynewby/Realtime-fast-style-transfer#1]
When I load the demo page, I get the following error in chrome debug console:

```
Uncaught (in promise) TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at webcam.min.js:2
```

Is this an incompatibility with latest Chrome, or is something else perhaps more mysterious going on?

**Comment by garynewby** [comment]
No problem loading in latest Brave Version 1.5.112 Chromium: 80.0.3987.132 (Official Build) (64-bit)
